### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by modamaan** [izam-mohammed/GemInsights#7]
<img width="1280" alt="gemini1" src="https://github.com/izam-mohammed/GemInsights/assets/121436543/14a461c5-f979-4ff0-b2a7-3fd62bd71713">

<img width="1280" alt="geminiInsights" src="https://github.com/izam-mohammed/GemInsights/assets/121436543/bdf56c40-a712-4474-80ac-30b0842eeb6c">

**Comment by modamaan** [comment]
use Render.com for deployment
it will work

**Comment by izam-mohammed** [comment]
We are working on it
